### ISSUE TITLE
Erro que não deixa a gente entrar nos produtos (ocorre apenas no deploy)

### ISSUE THREAD

**Issue by rtmr01** [Fcc2187/Projeto-FDS#46]
(antenv) root@itechdeployment_2b5ce576:/tmp/8dc819f6ce276f1# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contato, contenttypes, payment, sessions, store
Running migrations:
  Applying store.0010_alter_profile_cep_alter_profile_numero_and_more...Traceback (most recent call last):
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: ""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/8dc819f6ce276f1/manage.py", line 22, in <module>
    main()
  File "/tmp/8dc819f6ce276f1/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/_init_.py", line 442, in execute_from_command_line
    utility.execute()
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/_init_.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 893, in alter_field
    self._alter_field(
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/postgresql/schema.py", line 288, in _alter_field
    super()._alter_field(
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 1150, in _alter_field
    self.execute(
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/utils.py", line 91, in _exit_
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tmp/8dc819f6ce276f1/antenv/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.DataError: invalid input syntax for type integer: ""

**Comment by rtmr01** [comment]
A gente so reiniciou o banco de dados, era conflito
